
name: integration # can be named anything

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:  # can be named anything

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4   # checkout to the feature branch for performing actions
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies  # this is optional only for readability
      run: npm install

    - run: npm run build

  unit-tests:  # can be named anything

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4   # checkout to the feature branch for performing actions
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies  # this is optional only for readability
      run: npm install
      
    - name: "Run Unit Tests"
      run: npm run test

# Branch Protection Rule (if want to if all passed then only show merge button)
# go to setting of repo -> branhes -> add rule for main(target brach) branch -> select require status checks to pass before merging
